openapi: 3.1.1
info:
  title: Tracking Services API
  description: |
    The Tracking Services API provides tracking management services for completing validation flows.

    ## Features

    * **Tracking Completion**: Finalize tracking processes for onboarding and authentication flows
    * **Status Management**: Update tracking status with completion reasons
    * **Real-time Processing**: Fast response times for critical applications

  version: 1.0.0
  contact:
    name: FacePhi Support
    email: support@facephi.com
servers:
  - url: '{IDENTITY_API_BASE_URL}'
    description: Identity API Base URL
    variables:
      IDENTITY_API_BASE_URL:
        default: 'https://api.identity-platform.io'
security:
  - apiKey: []
tags:
  - name: Tracking
    description: Tracking management services for validation flows
paths:
  '/services/finishTracking':
    post:
      tags:
        - Tracking
      summary: Finish Tracking
      description: This service completes the tracking process and should be invoked upon completing all validations in the Onboarding or Authentication flows. **When this service is integrated, invoking the closeSession method from the Mobile/Web SDK is not required.**
      operationId: finishTracking
      requestBody:
        description: Tracking completion data with family type, status, and reason
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinishTrackingRequest'
            example:
              family: "OnBoarding"
              status: "SUCCEEDED"
              reason: "MANUAL_STATUS_CHANGE"
              extraData: "BQABAQG2gBNjuHN4kLmPqYf7R..."
      responses:
        '200':
          description: Tracking process completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FinishTrackingResponse'
              example:
                trackingStatus: 201
                trackingMessage: "FinishTrackingEvent: Ok"
                transactionId: "123e4567-e89b-12d3-a456-426614174000"
                timestamp: "2023-05-01T12:34:56.789Z"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadGatewayError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayTimeoutError'
      security:
        - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: API access authorization
  schemas:
    BadRequestError:
      type: object
      properties:
        status:
          type: integer
          example: 400
        title:
          type: string
          example: "Bad Request"
        detail:
          type: string
          example: "Invalid request."
        type:
          type: string
          example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400"
        errors:
          type: array
          example: []
    UnauthorizedError:
      type: object
      properties:
        message:
          type: string
          example: "Unauthorized"
    ForbiddenError:
      type: object
      properties:
        Message:
          type: string
          example: "User is not authorized to access this resource with an explicit deny"
    BadGatewayError:
      type: object
      properties:
        status:
          type: integer
          example: 502
        title:
          type: string
          example: "Bad Gateway"
        detail:
          type: string
          example: "Server got an invalid response."
        type:
          type: string
          example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502"
    GatewayTimeoutError:
      type: object
      properties:
        message:
          type: string
          example: "Endpoint request timed out"
    FinishTrackingRequest:
      type: object
      required:
        - family
        - status
        - reason
        - extraData
      properties:
        family:
          type: string
          description: "Possible values:"
          enum: ["Authentication", "OnBoarding"]
          example: "OnBoarding"
        status:
          type: string
          description: "Possible values:"
          enum: ["SUCCEEDED", "DENIED", "ERROR", "CANCELLED", "BLACKLISTED"]
          example: "SUCCEEDED"
        reason:
          type: string
          description: "Possible values:"
          enum: ["", "DOCUMENT_VALIDATION_NOT_PASSED", "DOCUMENT_VALIDATION_ERROR", "FACIAL_AUTHENTICATION_NOT_PASSED", "FACIAL_LIVENESS_NOT_PASSED", "FACIAL_AUTHENTICATION_ERROR", "FACIAL_LIVENESS_ERROR", "BLACKLISTED_FACE_TEMPLATE", "ALREADY_REGISTERED", "MANUAL_STATUS_CHANGE", "SECURITY_SERVICE_ERROR", "SELPHID_INTERNAL_ERROR", "SELPHID_TIMEOUT", "SELPHI_TIMEOUT"]
          example: "MANUAL_STATUS_CHANGE"
        extraData:
          type: string
          description: Token generated by Mobile/Web SDK. Contains tokenized tracking information.
          example: "BQABAQG2gBNjuHN4kLmPqYf7R..."
    FinishTrackingResponse:
      type: object
      properties:
        trackingStatus:
          type: integer
          description: Code indicating the result of the tracking service execution. Value **201** indicates service processed without exceptions.
          example: 201
        trackingMessage:
          type: string
          description: 'Message indicating the result of the tracking service execution. Value **"FinishTrackingEvent: Ok"**: Service processing without exceptions.'
          example: "FinishTrackingEvent: Ok"
        transactionId:
          type: string
          description: Transaction identifier associated with the request processed by the API.
          example: "123e4567-e89b-12d3-a456-426614174000"
        timestamp:
          type: string
          format: date-time
          description: Timestamp (UTC) of the response in the format YYYY-MM-DDThh:mm:ss.SSSZ.
          example: "2023-05-01T12:34:56.789Z"