openapi: 3.1.1
info:
  title: Civil Validation Ecuador - Facial Web API
  description: |
    Facial validation for Ecuador using web platform.
    This service performs facial matching against official images from the Civil Registry using biometric templates from web capture.
  version: 1.0.0
  contact:
    name: FacePhi Support
    email: support@facephi.com
servers:
  - url: '{IDENTITY_API_BASE_URL}'
    description: Identity API Base URL
    variables:
      IDENTITY_API_BASE_URL:
        default: 'https://api.identity-platform.io'
security:
  - apiKey: []
tags:
  - name: Civil Validation Ecuador
    description: Civil Registry validation services for Ecuador
paths:
  '/services/civilValidation':
    post:
      tags:
        - Civil Validation Ecuador
      summary: Facial Validation Web
      description: This service performs facial matching against official images from the Civil Registry for Ecuador using web platform.
      operationId: facialWeb
      requestBody:
        description: Facial validation request for web platform
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/facialWebRequest'
            example:
              operation: "FACIAL"
              platform: "WEB"
              templateRaw: "base64TemplateRawString"
              documentCode: "E8642I"
              documentNumber: "5678901234"
              countryCode: "ECU"
              returnPII: true
              tracking:
                extraData: "BQABAQG2gBNjuHN..."
                operationId: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
      responses:
        '200':
          description: Successfully processed facial validation - web
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CivilValidationFacialResponse'
              example:
                serviceResultCode: 0
                serviceResultLog: "NoneBecausePoseExceed"
                serviceTime: "1900"
                serviceFacialAuthenticationResult: 4
                serviceFacialAuthenticationHash: "GHI456JKL789MNO012PQR345STU678VWX901YZA234BCD567EFG890"
                serviceFacialSimilarityResult: 0.0
                serviceTransactionId: "86420135-8642-0135-7913-864201357913"
                civilServiceData: "{\"apellidos\":\"RAMIREZ MORENO\",\"nombres\":\"SOFIA ALEXANDRA\",\"fechaNacimiento\":\"13/04/1995\",\"sexo\":\"MUJER\",\"nacionalidad\":\"ECUATORIANA\",\"estadoCivil\":\"SOLTERO\"}"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '502':
          $ref: '#/components/responses/BadGateway'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
      security:
        - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: API access authorization
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              title:
                type: string
                example: "Bad Request"
              detail:
                type: string
                example: "Invalid request."
              type:
                type: string
                example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400"
              errors:
                type: array
                example: []
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Unauthorized"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              Message:
                type: string
                example: "User is not authorized to access this resource with an explicit deny"
    BadGateway:
      description: Bad Gateway
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 502
              title:
                type: string
                example: "Bad Gateway"
              detail:
                type: string
                example: "Server got an invalid response."
              type:
                type: string
                example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502"
    GatewayTimeout:
      description: Gateway Timeout
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Endpoint request timed out"
  schemas:
    TrackingInfo:
      type: object
      description: Object that represents necessary tracking information.
      properties:
        extraData:
          type: string
          format: byte
          description: Token generated by Mobile/Web SDK. Contains tokenized tracking information with Platform.
          example: "BQABAQG2gBNjuHN..."
        operationId:
          type: string
          description: Operation identifier generated by Mobile/Web SDK.
          example: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
    facialWebRequest:
      type: object
      required:
        - operation
        - platform
        - templateRaw
        - documentCode
        - documentNumber
        - countryCode
      properties:
        operation:
          type: string
          description: Validation operation to perform. For this endpoint, must be "FACIAL".
          enum: ["FACIAL"]
          example: "FACIAL"
        platform:
          type: string
          description: Platform on which the request is made. For this endpoint, must be "WEB".
          enum: ["WEB"]
          example: "WEB"
        templateRaw:
          type: string
          format: byte
          description: Biometric template, property generated by the Selphi widget. Required for FACIAL or FULL operations.
          example: "base64TemplateRawString"
        documentCode:
          type: string
          description: Document code (fingerprintCode), necessary for document validation in Ecuador. Required for Ecuador (ECU).
          example: "E8642I"
        documentNumber:
          type: string
          description: User's document number. Required for FACIAL operations.
          example: "5678901234"
        countryCode:
          type: string
          description: Country code in ISO 3166-1 alpha-3 format. Must be "ECU" for Ecuador.
          enum: ["ECU"]
          example: "ECU"
        returnPII:
          type: boolean
          description: Indicates if personal data generated by both the OCR service and the Civil Registry response is to be received.
          example: true
        tracking:
          $ref: '#/components/schemas/TrackingInfo'
    CivilDataValidationItem:
      type: object
      properties:
        field:
          type: string
          description: Field name being validated (e.g., firstName, lastName, dateOfBirth).
          example: "firstName"
        code:
          type: string
          description: |
            Validation result code:
            - "0": Validated ok
            - "-99": Possibly adulterated
            - Other codes may indicate specific validation issues
          example: "0"
        message:
          type: string
          description: Human-readable validation result message.
          example: "Validated ok"
    CivilValidationFacialResponse:
      type: object
      properties:
        serviceResultCode:
          type: integer
          description: Code indicating the overall result of the service execution. See [Service Result Code](/docs/services/serviceResultCodes#service-result-code)
          example: 0
        serviceTime:
          type: string
          description: Field indicating the processing time in milliseconds.
          example: "1900"
        serviceResultLog:
          type: string
          description: Descriptive field of the service execution result. Includes details when there is an error or exception in the module.
          example: "NoneBecausePoseExceed"
        serviceTransactionId:
          type: string
          description: Transaction identifier associated with the request processed by the API.
          example: "86420135-8642-0135-7913-864201357913"
        civilDataValidation:
          type: array
          description: Array representing the OCR validations against the data obtained from the Civil Registry. The presence of this object depends on the consulted Civil Registry.
          items:
            $ref: '#/components/schemas/CivilDataValidationItem'
        serviceFacialAuthenticationResult:
          type: integer
          description: Code indicating the result of the facial matching. See [Service Facial Authentication Result](/docs/services/serviceResultCodes#service-facial-authentication-result)
          example: 4
        serviceFacialAuthenticationHash:
          type: string
          description: Integrity hash of the biometric template used in a positive or uncertain facial authentication.
          example: "GHI456JKL789MNO012PQR345STU678VWX901YZA234BCD567EFG890"
        serviceFacialSimilarityResult:
          type: number
          format: float
          description: Value indicating the facial similarity between the face in the identity document photo and the selfie taken by the user. 1.0 = 100%.
          example: 0.0
        serviceDocument:
          type: string
          description: JSON string representing the captured document. Its properties are all the fields extracted by the OCR process.
          example: "{\"DocumentNumber\":\"5678901234\",\"FirstName\":\"SOFIA ALEXANDRA\",\"LastName\":\"RAMIREZ MORENO\"}"
        civilServiceData:
          type: string
          description: JSON string representing the personal data obtained from the Civil Registry (returned only if returnPII was sent as true in the request).
          example: "{\"apellidos\":\"RAMIREZ MORENO\",\"nombres\":\"SOFIA ALEXANDRA\",\"fechaNacimiento\":\"13/04/1995\"}"