openapi: 3.1.1
info:
  title: Morphology Services API V1
  description: |
    The Morphology Services API V1 provides document validation capabilities through morphological analysis of identity documents.
    
    ## Features
    
    * **Document Validation**: Morphological validation process for identity documents
    * **Multi-step Process**: Start, Status, and Data retrieval workflow
    * **Multiple Document Types**: Support for passport, driving license, ID card, and visa
    * **Real-time Processing**: Asynchronous processing with status monitoring
    
    **Note**: This is the legacy V1 API. For enhanced features, see the V2 API documentation.
    
  version: 1.0.0
  contact:
    name: FacePhi Support
    email: support@facephi.com
servers:
  - url: '{IDENTITY_API_BASE_URL}'
    description: Identity API Base URL
    variables:
      IDENTITY_API_BASE_URL:
        default: 'https://api.identity-platform.io'
security:
  - apiKey: []
tags:
  - name: Morphology V1
    description: Legacy document validation services through morphological analysis
paths:
  '/verify/documentValidation/start':
    post:
      tags:
        - Morphology V1
      summary: Document Validation Start
      description: Start the morphological validation process of identity documents by sending the **document images, country and type** of document to be analyzed.
      operationId: documentValidationStart
      requestBody:
        description: Document validation start request with images and metadata
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentValidationStartRequest'
            example:
              country: "ESP"
              idType: "ID_CARD"
              frontsideImage: "BAMBAQLNHJoWGPjfeuDIzDXdZuP..."
              backsideImage: "BAMBAQLNHJoWGPjfeuDIzDXdZuP..."
              merchantIdScanReference: "my-scan-ref-001"
      responses:
        '200':
          description: Document validation process started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentValidationStartResponse'
              example:
                timestamp: "1970-01-01T00:00:00.000Z"
                scanReference: "fe294c25-17e1-4d98-a958-710edbf00064"
                type: "1"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadGatewayError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayTimeoutError'
      security:
        - apiKey: []

  '/verify/documentValidation/status':
    post:
      tags:
        - Morphology V1
      summary: Document Validation Status
      description: Query the status of the morphological validation operation. Call this endpoint **repeatedly** until the analysis operation is completed. See [Document Validation Status Values](/docs/services/morphology#document-validation-status-values) for reference on the different status values.
      operationId: documentValidationStatus
      requestBody:
        description: Status request with scan reference
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentValidationStatusRequest'
            example:
              scanReference: "fe294c25-17e1-4d98-a958-710edbf00064"
              type: "1"
      responses:
        '200':
          description: Status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentValidationStatusResponse'
              example:
                timestamp: "1970-01-01T00:00:00.000Z"
                scanReference: "fe294c25-17e1-4d98-a958-710edbf00064"
                status: "DONE"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadGatewayError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayTimeoutError'
      security:
        - apiKey: []

  '/verify/documentValidation/data':
    post:
      tags:
        - Morphology V1
      summary: Document Validation Data
      description: |
        Retrieve the results of the morphological analysis of the document **once the validation process has completed successfully**.

        **Note:** The response fields will depend on the configured morphology provider.
      operationId: documentValidationData
      requestBody:
        description: Data request with scan reference
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentValidationDataRequest'
            example:
              scanReference: "fe294c25-17e1-4d98-a958-710edbf00064"
              type: "1"
      responses:
        '200':
          description: Validation data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentValidationDataResponse'
              example:
                document:
                  dateOfBirthParts:
                    year: "1995"
                    month: "10"
                    day: "16"
                  dob: "XXXX-10-16"
                  expiry: "XXXX-10-16"
                  expiryDateParts:
                    year: "XXXX"
                    month: "XX"
                    day: "XX"
                  firstName: "XXX XXXXX"
                  gender: null
                  idSubtype: null
                  issuingCountry: "CHL"
                  lastName: "XXXX XXXXXX"
                  nationality: null
                  number: "XXXXXXXXX"
                  optionalData2: "XXXXXX K"
                  status: "APPROVED_VERIFIED"
                  type: "ID_CARD"
                  issuingDate: null
                  issuingDateParts: null
                  issuingPlace: null
                  issuingAuthority: null
                transaction:
                  date: "2024-01-18T17:48:49.598029Z"
                  merchantScanReference: "680f8ef8-3ff5-XXXXX-XXXX-97182d998dfb"
                  source: "API"
                  status: "DONE"
                  updatedAt: "2024-01-18T17:49:15.310078Z"
                verification:
                  additionalChecks: null
                  mrzCheck: null
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadGatewayError'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayTimeoutError'
      security:
        - apiKey: []

components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: API access authorization
  schemas:
    BadRequestError:
      type: object
      properties:
        status:
          type: integer
          example: 400
        title:
          type: string
          example: "Bad Request"
        detail:
          type: string
          example: "Invalid request."
        type:
          type: string
          example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400"
        errors:
          type: array
          example: []
    UnauthorizedError:
      type: object
      properties:
        message:
          type: string
          example: "Unauthorized"
    ForbiddenError:
      type: object
      properties:
        Message:
          type: string
          example: "User is not authorized to access this resource with an explicit deny"
    BadGatewayError:
      type: object
      properties:
        status:
          type: integer
          example: 502
        title:
          type: string
          example: "Bad Gateway"
        detail:
          type: string
          example: "Server got an invalid response."
        type:
          type: string
          example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502"
    GatewayTimeoutError:
      type: object
      properties:
        message:
          type: string
          example: "Endpoint request timed out"
    DocumentValidationStartRequest:
      type: object
      required:
        - country
        - idType
        - frontsideImage
      properties:
        country:
          type: string
          description: ISO 3166-1 alpha-3 country code
          example: "ESP"
        idType:
          type: string
          description: Type of the provided ID
          enum: ["PASSPORT", "DRIVING_LICENSE", "ID_CARD", "VISA"]
          example: "ID_CARD"
        frontsideImage:
          type: string
          format: byte
          description: Base64 encoded open or tokenized image of ID front side
          example: "BAMBAQLNHJoWGPjfeuDIzDXdZuP..."
        backsideImage:
          type: string
          format: byte
          description: Base64 encoded open or tokenized image of ID back side. Optional for single-sided documents like PASSPORT
          example: "BAMBAQLNHJoWGPjfeuDIzDXdZuP..."
        merchantIdScanReference:
          type: string
          description: Custom operation reference. Max. length 100 characters
          maxLength: 100
          example: "my-scan-ref-001"
    DocumentValidationStartResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp (UTC) of the response in ISO 8601 format
          example: "1970-01-01T00:00:00.000Z"
        scanReference:
          type: string
          description: Reference number for each scan
          example: "fe294c25-17e1-4d98-a958-710edbf00064"
        type:
          type: string
          description: Deprecated value. Will be removed in future versions
          example: "1"
          deprecated: true
    DocumentValidationStatusRequest:
      type: object
      required:
        - scanReference
      properties:
        scanReference:
          type: string
          description: Scan reference number
          example: "fe294c25-17e1-4d98-a958-710edbf00064"
        type:
          type: string
          description: Deprecated value. Will be removed in future versions
          example: "1"
          deprecated: true
    DocumentValidationStatusResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          description: Timestamp (UTC) of the response in ISO 8601 format
          example: "1970-01-01T00:00:00.000Z"
        scanReference:
          type: string
          description: Scan reference number
          example: "fe294c25-17e1-4d98-a958-710edbf00064"
        status:
          type: string
          description: Operation status
          enum: ["PENDING", "DONE", "FAILED"]
          example: "DONE"
    DocumentValidationDataRequest:
      type: object
      required:
        - scanReference
      properties:
        scanReference:
          type: string
          description: Scan reference number
          example: "fe294c25-17e1-4d98-a958-710edbf00064"
        type:
          type: string
          description: Deprecated value. Will be removed in future versions
          example: "1"
          deprecated: true
    DocumentValidationDataResponse:
      type: object
      properties:
        document:
          type: object
          description: Document validation details and extracted information
          properties:
            dateOfBirthParts:
              type: object
              nullable: true
              properties:
                year:
                  type: string
                  nullable: true
                month:
                  type: string
                  nullable: true
                day:
                  type: string
                  nullable: true
            dob:
              type: string
              nullable: true
              description: Date of birth in YYYY-MM-DD format
            expiry:
              type: string
              nullable: true
              description: Document expiry date in YYYY-MM-DD format
            expiryDateParts:
              type: object
              nullable: true
              properties:
                year:
                  type: string
                  nullable: true
                month:
                  type: string
                  nullable: true
                day:
                  type: string
                  nullable: true
            firstName:
              type: string
              nullable: true
              description: First name of the document holder
            lastName:
              type: string
              nullable: true
              description: Last name of the document holder
            gender:
              type: string
              nullable: true
              description: Gender of the document holder
            idSubtype:
              type: string
              nullable: true
              description: Document subtype
            issuingCountry:
              type: string
              nullable: true
              description: Country that issued the document
            nationality:
              type: string
              nullable: true
              description: Nationality of the document holder
            number:
              type: string
              nullable: true
              description: Document number
            optionalData2:
              type: string
              nullable: true
              description: Additional optional data field
            status:
              type: string
              description: Document verification status. See [Document Status Results](/docs/services/morphology#document-status-results) for reference on the different status values. 
              enum: ["APPROVED_VERIFIED", "DENIED_FRAUD", "DENIED_UNSUPPORTED_ID_TYPE", "DENIED_UNSUPPORTED_ID_COUNTRY", "ERROR_NOT_READABLE"]
            type:
              type: string
              nullable: true
              description: Document type
              enum: ["PASSPORT", "DRIVING_LICENSE", "ID_CARD", "VISA"]
            issuingDate:
              type: string
              nullable: true
              description: Document issuing date
            issuingDateParts:
              type: object
              nullable: true
              properties:
                year:
                  type: string
                  nullable: true
                month:
                  type: string
                  nullable: true
                day:
                  type: string
                  nullable: true
            issuingPlace:
              type: string
              nullable: true
              description: Place where the document was issued
            issuingAuthority:
              type: string
              nullable: true
              description: Authority that issued the document
        transaction:
          type: object
          description: Transaction metadata and processing information
          properties:
            date:
              type: string
              format: date-time
              description: Transaction creation date in ISO 8601 format
            merchantScanReference:
              type: string
              description: Merchant-provided scan reference
            source:
              type: string
              description: Source of the transaction
              example: "API"
            status:
              type: string
              description: Transaction processing status
              enum: ["DONE"]
            updatedAt:
              type: string
              format: date-time
              description: Last update timestamp in ISO 8601 format
        verification:
          type: object
          description: Verification results and additional checks performed
          properties:
            additionalChecks:
              type: object
              nullable: true
              description: Additional verification checks performed
            mrzCheck:
              type: object
              nullable: true
              description: Machine Readable Zone verification results

