openapi: 3.1.1
info:
  title: Services API
  description: |
    The Services API provides identity verification and biometric services.
    
    ## Features
    
    * **Passive Liveness Detection**: Verify if a selfie image shows a live person
    * **Identity Verification**: Comprehensive identity validation services
    * **Real-time Processing**: Fast response times for critical applications
    
  version: 1.0.0
  contact:
    name: FacePhi Support
    email: support@facephi.com
servers:
  - url: '{IDENTITY_API_BASE_URL}'
    description: Identity API Base URL
    variables:
      IDENTITY_API_BASE_URL:
        default: 'https://api.identity-platform.io'
security:
  - apiKey: []
tags:
  - name: Services
    description: Identity verification and biometric services
paths:
  '/services/evaluatePassiveLivenessToken':
    post:
      tags:
        - Services
      summary: Evaluate Passive Liveness Token
      description: This service performs a liveness check using the best tokenized image obtained during the user's selfie capture. To generate the tokenized image, the native function of the Selphi widget is used, with the bestImage parameter (open image) generated by the widget.
      operationId: evaluatePassiveLivenessToken
      requestBody:
        description: Tokenized image data and tracking information for liveness evaluation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PassiveLivenessTokenRequest'
            example:
              imageBuffer: "BAMBAQLNHJoWGPjfeuDIzDXdZuP/…"
              tracking:
                extraData: "BQABAQG2gBNjuHN..."
                operationId: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
      responses:
        '200':
          description: Successfully processed liveness evaluation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PassiveLivenessResponse'
              examples:
                Live:
                  summary: Live detection result
                  value:
                    serviceResultCode: 0
                    serviceResultLog: "Live"
                    serviceTime: "799"
                    serviceTransactionId: "35d93da8-b843-4033-8e78-c0aabedcef8b"
                    serviceLivenessResult: 3
                NoLive:
                  summary: No live detection result
                  value:
                    serviceResultCode: 0
                    serviceResultLog: "NoLive"
                    serviceTime: "81"
                    serviceTransactionId: "3f332c81-3dfa-4952-b593-20e3b5651b5b"
                    serviceLivenessResult: 0
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
              example:
                message: "Unauthorized"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  Message:
                    type: string
                    example: "User is not authorized to access this resource with an explicit deny"
              example:
                Message: "User is not authorized to access this resource with an explicit deny"
      security:
        - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: API key for authentication
  schemas:
    PassiveLivenessTokenRequest:
      type: object
      required:
        - imageBuffer
      properties:
        imageBuffer:
          type: string
          format: byte
          description: BestImage property generated by the Selphi widget and tokenized using the widget's native function.
          example: "BAMBAQLNHJoWGPjfeuDIzDXdZuP/…"
        tracking:
          $ref: '#/components/schemas/TrackingInfo'
    TrackingInfo:
      type: object
      description: Object that represents necessary tracking information.
      properties:
        extraData:
          type: string
          format: byte
          description: Token generated by Mobile/Web SDK. Contains tokenized tracking information with Platform.
          example: "BQABAQG2gBNjuHN..."
        operationId:
          type: string
          description: Operation identifier generated by Mobile/Web SDK.
          example: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
    PassiveLivenessResponse:
      type: object
      properties:
        serviceResultCode:
          type: integer
          description: Code indicating the overall result of the service execution. See Table 1 - Service Result Code
          example: 0
        serviceTime:
          type: string
          description: Total response time (milliseconds).
          example: "799"
        serviceLivenessResult:
          type: integer
          description: Code indicating the result of the passive liveness test evaluation. See Table 3 - Service Liveness Result
          example: 3
        serviceResultLog:
          type: string
          description: Descriptive field of the service execution result. Includes details when there is an error or exception.
          example: "Live"
        serviceTransactionId:
          type: string
          description: Transaction identifier associated with the request processed by the API.
          example: "35d93da8-b843-4033-8e78-c0aabedcef8b"