openapi: 3.1.1
info:
  title: Civil Validation Costa Rica - Facial Mobile API
  description: |
    Facial validation for Costa Rica using mobile platform.
    This service performs facial matching against official images from the Civil Registry using biometric templates.
  version: 1.0.0
  contact:
    name: FacePhi Support
    email: support@facephi.com
servers:
  - url: '{IDENTITY_API_BASE_URL}'
    description: Identity API Base URL
    variables:
      IDENTITY_API_BASE_URL:
        default: 'https://api.identity-platform.io'
security:
  - apiKey: []
tags:
  - name: Civil Validation Costa Rica
    description: Civil Registry validation services for Costa Rica
paths:
  '/services/civilValidation':
    post:
      tags:
        - Civil Validation Costa Rica
      summary: Facial Validation Mobile
      description: This service performs facial matching against official images from the Civil Registry for Costa Rica using mobile platform.
      operationId: facialMobile
      requestBody:
        description: Facial validation request for mobile platform
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/facialMobileRequest'
            example:
              operation: "FACIAL"
              platform: "MOBILE"
              templateRaw: "{{templateRawCRI}}"
              documentNumber: "1 0627 0723"
              countryCode: "CRI"
              tracking:
                extraData: "BQABAQG2gBNjuHN..."
                operationId: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
      responses:
        '200':
          description: Successfully processed facial validation - mobile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CivilValidationFacialResponse'
              example:
                serviceResultCode: 0
                serviceTime: "2800"
                serviceResultLog: "Service executed ok"
                serviceTransactionId: "24681357-2468-1357-9024-246813579024"
                civilDataValidation:
                  - field: "firstName"
                    code: "-99"
                    message: "Possibly adulterated"
                  - field: "lastName"
                    code: "0"
                    message: "Validated ok"
                  - field: "dateOfBirth"
                    code: "0"
                    message: "Validated ok"
                serviceFacialAuthenticationResult: 3
                serviceFacialSimilarityResult: 0.94
                serviceFacialAuthenticationHash: "NA"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '502':
          $ref: '#/components/responses/BadGateway'
        '504':
          $ref: '#/components/responses/GatewayTimeout'
      security:
        - apiKey: []
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
      description: API access authorization
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              title:
                type: string
                example: "Bad Request"
              detail:
                type: string
                example: "Invalid request."
              type:
                type: string
                example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400"
              errors:
                type: array
                example: []
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Unauthorized"
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              Message:
                type: string
                example: "User is not authorized to access this resource with an explicit deny"
    BadGateway:
      description: Bad Gateway
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 502
              title:
                type: string
                example: "Bad Gateway"
              detail:
                type: string
                example: "Server got an invalid response."
              type:
                type: string
                example: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502"
    GatewayTimeout:
      description: Gateway Timeout
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Endpoint request timed out"
  schemas:
    TrackingInfo:
      type: object
      description: Object that represents necessary tracking information.
      properties:
        extraData:
          type: string
          format: byte
          description: Token generated by Mobile/Web SDK. Contains tokenized tracking information with Platform.
          example: "BQABAQG2gBNjuHN..."
        operationId:
          type: string
          description: Operation identifier generated by Mobile/Web SDK.
          example: "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"
    facialMobileRequest:
      type: object
      required:
        - operation
        - platform
        - templateRaw
        - countryCode
      properties:
        operation:
          type: string
          description: Validation operation to perform. For this endpoint, must be "FACIAL".
          enum: ["FACIAL"]
          example: "FACIAL"
        platform:
          type: string
          description: Platform on which the request is made. For this endpoint, must be "MOBILE".
          enum: ["MOBILE"]
          example: "MOBILE"
        templateRaw:
          type: string
          format: byte
          description: Biometric template, property generated by the Selphi widget. Required for FACIAL or FULL operations.
          example: "{{templateRawCRI}}"
        documentNumber:
          type: string
          description: User's document number. Required for FACIAL operations in Costa Rica.
          example: "1 0627 0723"
        countryCode:
          type: string
          description: Country code in ISO 3166-1 alpha-3 format. Must be "CRI" for Costa Rica.
          enum: ["CRI"]
          example: "CRI"
        tracking:
          $ref: '#/components/schemas/TrackingInfo'
    CivilDataValidationItem:
      type: object
      properties:
        field:
          type: string
          description: Field name being validated (e.g., firstName, lastName, dateOfBirth).
          example: "firstName"
        code:
          type: string
          description: |
            Validation result code:
            - "0": Validated ok
            - "-99": Possibly adulterated
            - Other codes may indicate specific validation issues
          example: "0"
        message:
          type: string
          description: Human-readable validation result message.
          example: "Validated ok"
    CivilValidationFacialResponse:
      type: object
      properties:
        serviceResultCode:
          type: integer
          description: Code indicating the overall result of the service execution. See [Service Result Code](/docs/services/serviceResultCodes#service-result-code)
          example: 0
        serviceTime:
          type: string
          description: Field indicating the processing time in milliseconds.
          example: "2800"
        serviceResultLog:
          type: string
          description: Descriptive field of the service execution result. Includes details when there is an error or exception in the module.
          example: "Service executed ok"
        serviceTransactionId:
          type: string
          description: Transaction identifier associated with the request processed by the API.
          example: "24681357-2468-1357-9024-246813579024"
        civilDataValidation:
          type: array
          description: Array representing the OCR validations against the data obtained from the Civil Registry. The presence of this object depends on the consulted Civil Registry.
          items:
            $ref: '#/components/schemas/CivilDataValidationItem'
        serviceFacialAuthenticationResult:
          type: integer
          description: Code indicating the result of the facial matching. See [Service Facial Authentication Result](/docs/services/serviceResultCodes#service-facial-authentication-result)
          example: 3
        serviceFacialAuthenticationHash:
          type: string
          description: Integrity hash of the biometric template used in a positive or uncertain facial authentication.
          example: "NA"
        serviceFacialSimilarityResult:
          type: number
          format: float
          description: Value indicating the facial similarity between the face in the identity document photo and the selfie taken by the user. 1.0 = 100%.
          example: 0.94